export const ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",

  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",

  VALIDATION_ERROR:
    "VALIDATION_ERROR",

  UNAUTHORIZED:
    "UNAUTHORIZED",

  INTERNAL_ERROR:
    "INTERNAL_ERROR"
};